python 1.py | tee log/1.out
python 2.py | tee log/2.out
python 3.py | tee log/3.out
python 4.py | tee log/4.out
python 5.py | tee log/5.out
python 6.py | tee log/6.out
python 7.py | tee log/7.out
python 8.py | tee log/8.out
python 9.py | tee log/9.out
python 10.py | tee log/10.out
